name: Deploy Feature Infrastructure using Bicep

on:
  push:
    branches:
      - feat/stbr-infra
      - feat/FN-1261/add-healthcheck-on-webapps
    paths:
      - '.github/workflows/bicep_az_deployment_group.yml'
      - '.github/workflows/bicep_deploy.yml'
      - '.github/workflows/bicep_workflow_feature.yml'
      - 'infrastructure/resource_group_level/**'
  workflow_dispatch:

# TODO:FN-944 Set permissions to restrict to Workload Identities

jobs:
  lint:
    name: Lint Bicep code
    runs-on: [self-hosted, linux, deployment]
    steps:
    - uses: actions/checkout@v3

    - name: Install Bicep
      run: |
        az config set bicep.use_binary_from_path=False
        az bicep install
        az bicep upgrade

    - name: Lint Bicep Code
      run: |
        az bicep version
        az bicep build --file infrastructure/resource_group_level/main.bicep

  deploy-feature:
    name: Deploy to Feature Environment

    uses:  ./.github/workflows/bicep_deploy.yml
    needs: lint
    with:
      environment: feature
      resourceGroupName: Digital-Feature
    secrets: inherit
