name: PR tests - Number Generator Function App

on:
  pull_request:
    branches: [ main, amendments ]
    paths:
    - 'azure-functions/number-generator-function/**'
  schedule:
    # A weekly run to roll up any base image patches,
    # in office hours, avoiding bank holiday Mondays:
    # "At 12:00 on Tuesday." - https://crontab.guru/
    - cron: '0 12 * * 2'

env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
    - name: Initialise Environment
      run: |
        echo Setting environment to ${{ env.environment }}

  build:
    name: Build and push Number Generator Azure Function
    runs-on: ubuntu-latest
    needs: set-environment
    environment:
      name: E2ETEST
    steps:
    - uses: actions/checkout@v2
    - name: Commit hash
      run: "echo GITHUB_SHA=${{ github.sha }}"
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
        repository: azure-function-number-generator
        path: azure-functions/number-generator-function
        tags: ${{ github.sha }}
        build_args: GITHUB_SHA=${{ github.sha }}
        add_git_labels: true

  test:
    name: Run PR tests
    needs: [set-environment, build]
    environment:
      name: E2ETEST
    runs-on: ubuntu-latest
    env:
      AZURE_PORTAL_STORAGE_ACCOUNT: ${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }}
      AZURE_PORTAL_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_PORTAL_STORAGE_ACCESS_KEY }}
      MULESOFT_API_KEY: ${{ secrets.MULESOFT_API_KEY }}
      MULESOFT_API_SECRET: ${{ secrets.MULESOFT_API_SECRET }}
      MULESOFT_API_UKEF_TF_EA_URL: ${{ secrets.MULESOFT_API_UKEF_TF_EA_URL }}
    steps:
    - uses: actions/checkout@v2
    # Pull the latest images to run with so we don't need to build them
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
    - name: Pull Number Generator Function
      run: |
        docker pull ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:${{ github.sha }}
        docker tag ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:${{ github.sha }} dtfs/azure-function-number-generator
    - name: Start Docker Compose
      run: |
        source secrets/set_jwt_keypair.sh
        docker-compose -f docker-compose.yml up -d number-generator-function
        echo "waiting 10 seconds to ensure mongo db has started before we run integration tests against it.."
        sleep 10
