name: PR tests - Reference Data Proxy

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'reference-data-proxy/**'

env:
  environment: dev
  # Credentials for accessing Azure
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  set-environment:
    name: Set Environment
    runs-on: self-hosted
    outputs:
      environment: ${{ env.environment }}
    steps:
    - name: Initialise Environment
      run: |
        echo Setting environment to ${{ env.environment }}

  build:
    name: Build and push Reference Data Proxy
    runs-on: self-hosted
    needs: set-environment
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Commit hash
      run: "echo GITHUB_SHA=${{ github.sha }}"
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
        repository: reference-data-proxy
        path: reference-data-proxy
        tags: ${{ github.sha }}
        build_args: GITHUB_SHA=${{ github.sha }}
        add_git_labels: true

  test:
    name: "Run PR tests"
    needs: [set-environment, build]
    environment:
      name: APITEST
    runs-on: self-hosted
    env:
      MULESOFT_API_KEY: ${{ secrets.MULESOFT_API_KEY }}
      MULESOFT_API_SECRET: ${{ secrets.MULESOFT_API_SECRET }}
      MULESOFT_API_NUMBER_GENERATOR_URL: ${{ secrets.MULESOFT_API_NUMBER_GENERATOR_URL }}
      MULESOFT_API_ACBS_DEAL_URL: ${{ secrets.MULESOFT_API_ACBS_DEAL_URL }}
      MULESOFT_API_ACBS_FACILITY_URL: ${{ secrets.MULESOFT_API_ACBS_FACILITY_URL }}
      MULESOFT_API_PARTY_DB_KEY: ${{ secrets.MULESOFT_API_PARTY_DB_KEY }}
      MULESOFT_API_PARTY_DB_SECRET: ${{ secrets.MULESOFT_API_PARTY_DB_SECRET }}
      MULESOFT_API_PARTY_DB_URL: ${{ secrets.MULESOFT_API_PARTY_DB_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET }}
      MULESOFT_API_EXPOSURE_PERIOD_URL: ${{ secrets.MULESOFT_API_EXPOSURE_PERIOD_URL }}

      MULESOFT_API_UKEF_ESTORE_EA_URL: ${{ secrets.MULESOFT_API_UKEF_ESTORE_EA_URL }}
      MULESOFT_API_UKEF_ESTORE_EA_KEY: ${{ secrets.MULESOFT_API_UKEF_ESTORE_EA_KEY }}
      MULESOFT_API_UKEF_ESTORE_EA_SECRET: ${{ secrets.MULESOFT_API_UKEF_ESTORE_EA_SECRET }}

      ORDNANCE_SURVEY_API_URL: ${{ secrets.ORDNANCE_SURVEY_API_URL }}
      ORDNANCE_SURVEY_API_KEY: ${{ secrets.ORDNANCE_SURVEY_API_KEY }}

      MULESOFT_API_UKEF_MDM_EA_URL: ${{ secrets.MULESOFT_API_UKEF_MDM_EA_URL }}
      MULESOFT_API_UKEF_MDM_EA_KEY: ${{ secrets.MULESOFT_API_UKEF_MDM_EA_KEY }}
      MULESOFT_API_UKEF_MDM_EA_SECRET: ${{ secrets.MULESOFT_API_UKEF_MDM_EA_SECRET }}

      COMPANIES_HOUSE_API_URL: ${{ secrets.COMPANIES_HOUSE_API_URL }}
      COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY }}

      UKEF_TFM_API_SYSTEM_KEY: ${{ secrets.UKEF_TFM_API_SYSTEM_KEY }}
      UKEF_TFM_API_REPORTS_KEY: ${{ secrets.UKEF_TFM_API_REPORTS_KEY }}

      GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    # Pull the latest images to run with so we don't need to build them
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
    - name: Pull reference-data-proxy
      run: |
        docker pull ${{ secrets.ACR_REGISTRY_DEV }}/reference-data-proxy:${{ github.sha }}
        docker tag ${{ secrets.ACR_REGISTRY_DEV }}/reference-data-proxy:${{ github.sha }} dtfs/reference-data-proxy
    - name: Start Docker Compose
      run: |
        docker-compose up -d reference-data-proxy
    - name: Run API tests
      run: |
        docker-compose exec -T reference-data-proxy npm run api-test


    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#dtfs-github-actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()
