name: PR - External APIs

on:
  pull_request:
    branches: [main]
    paths:
      - "reference-data-proxy/**"

env:
  environment: dev
  # Credentials for accessing Azure
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  lint:
    name: Linting
    defaults:
      run:
        working-directory: portal-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#dtfs-github-actions"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  workflow-build-third-party-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_third-party-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  test:
    name: "Run PR tests"
    needs: [lint, workflow-build-third-party-api]
    runs-on: ubuntu-latest
    env:
      MULESOFT_API_KEY: ${{ secrets.MULESOFT_API_KEY }}
      MULESOFT_API_SECRET: ${{ secrets.MULESOFT_API_SECRET }}
      MULESOFT_API_NUMBER_GENERATOR_URL: ${{ secrets.MULESOFT_API_NUMBER_GENERATOR_URL }}
      MULESOFT_API_ACBS_DEAL_URL: ${{ secrets.MULESOFT_API_ACBS_DEAL_URL }}
      MULESOFT_API_ACBS_FACILITY_URL: ${{ secrets.MULESOFT_API_ACBS_FACILITY_URL }}
      MULESOFT_API_PARTY_DB_KEY: ${{ secrets.MULESOFT_API_PARTY_DB_KEY }}
      MULESOFT_API_PARTY_DB_SECRET: ${{ secrets.MULESOFT_API_PARTY_DB_SECRET }}
      MULESOFT_API_PARTY_DB_URL: ${{ secrets.MULESOFT_API_PARTY_DB_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET: ${{ secrets.MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET }}
      MULESOFT_API_EXPOSURE_PERIOD_URL: ${{ secrets.MULESOFT_API_EXPOSURE_PERIOD_URL }}

      UKEF_TFM_API_SYSTEM_KEY: ${{ secrets.UKEF_TFM_API_SYSTEM_KEY }}
      UKEF_TFM_API_REPORTS_KEY: ${{ secrets.UKEF_TFM_API_REPORTS_KEY }}

      GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      # Pull the latest images to run with so we don't need to build them
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_DEV }}
          username: ${{ secrets.ACR_USERNAME_DEV }}
          password: ${{ secrets.ACR_PASSWORD_DEV }}
      - name: Pull reference-data-proxy
        run: |
          docker pull ${{ secrets.ACR_REGISTRY_DEV }}/reference-data-proxy:${{ github.sha }}
          docker tag ${{ secrets.ACR_REGISTRY_DEV }}/reference-data-proxy:${{ github.sha }} dtfs/reference-data-proxy
      - name: Start Docker Compose
        run: |
          docker-compose up -d reference-data-proxy
      - name: Run API tests
        run: |
          docker-compose exec -T reference-data-proxy npm run api-test
      # - uses: act10ns/slack@v1
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: "#dtfs-github-actions"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: failure()