# DTFS Git Hub Actions
#####################################
# This GHA is responsible for release version updates.

name: Automated release
run-name: Executing release on ${{ github.repository }} ğŸš€

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  # 1. `package.json`, `README.md` and `CHANGELOG.md` updates
  release:
    name: Release setup ğŸ”§
    runs-on: ubuntu-latest
    steps:
      - name: Release version âš¡ï¸
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          target-branch: main
